### ISSUE TITLE
Add support for Cucumber metadata in Cargo.toml

### ISSUE THREAD

**Issue by bbqsrc** [bbqsrc/cucumber-rust#101]
We would provide support for default settings for the Cucumber runners for a project in the `package.metadata.cucumber` section of the `Cargo.toml`. First thing to support would be the default language to assume, as adding your preferred language to _every_ feature file surely becomes tedious.

```toml
[package.metadata.cucumber]
language = "fr"
```
