### ISSUE TITLE
Documentation Example does not build

### ISSUE THREAD

**Issue by aaronmcohen** [bbqsrc/cucumber-rust#104]
The instructions from https://github.com/bbqsrc/cucumber-rust do not compile with rust 1.5.0 or nightly.

# Steps to reproduce
- Create project
> cargo new cucumeber-example --lib --edition 2018  --name cucumber-example
- cd cucumeber-example 
- Update Cargo.toml
```toml
[package]
name = "cucumber-example"
version = "0.1.0"
authors = ["Aaron Cohen <aaronmcohen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "0.8.2", features = ["macros"] }
# You can use any executor you want, but we're going to use Tokio in this example.
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
```
- mkdir features
- Updates features/example.feature
```gherkin
Feature: Example feature

  Scenario: An example scenario
    Given I am trying out Cucumber
    When I consider what I am doing
    Then I am interested in ATDD
    And we can implement rules with regex
```
- mkdir tests
- Update tests/cucumber.ts
```rust
use std::{cell::RefCell, convert::Infallible};

use cucumber::{async_trait, given, then, when, World, WorldInit};

#[derive(WorldInit)]
pub struct MyWorld {
    // You can use this struct for mutable context in scenarios.
    foo: String,
    bar: usize,
    some_value: RefCell<u8>,
}

impl MyWorld {
    async fn test_async_fn(&mut self) {
        *self.some_value.borrow_mut() = 123u8;
        self.bar = 123;
    }
}

#[async_trait(?Send)]
impl World for MyWorld {
    type Error = Infallible;

    async fn new() -> Result<Self, Infallible> {
        Ok(Self {
            foo: "wat".into(),
            bar: 0,
            some_value: RefCell::new(0),
        })
    }
}

#[given("a thing")]
async fn a_thing(world: &mut MyWorld) {
    world.foo = "elho".into();
    world.test_async_fn().await;
}

#[when(regex = "something goes (.*)")]
async fn something_goes(_: &mut MyWorld, _wrong: String) {}

#[given("I am trying out Cucumber")]
fn i_am_trying_out(world: &mut MyWorld) {
    world.foo = "Some string".to_string();
}

#[when("I consider what I am doing")]
fn i_consider(world: &mut MyWorld) {
    let new_string = format!("{}.", &world.foo);
    world.foo = new_string;
}

#[then("I am interested in ATDD")]
fn i_am_interested(world: &mut MyWorld) {
    assert_eq!(world.foo, "Some string.");
}

#[then(regex = r"^we can (.*) rules with regex$")]
fn we_can_regex(_: &mut MyWorld, action: String) {
    // `action` can be anything implementing `FromStr`.
    assert_eq!(action, "implement");
}

#[tokio::main]
async fn main() {
    let runner = MyWorld::init(&["./features"]);
    runner.run_and_exit().await;
}
```
The build fails with 
```
cargo test --test cucumber 
   Compiling cucumber-example v0.1.0 (/Users/amcohen@us.ibm.com/Projects/cucumeber-example)
   Compiling proc-macro2 v1.0.24
   Compiling syn v1.0.60
   Compiling memchr v2.3.4
   Compiling libc v0.2.86
   Compiling serde_derive v1.0.123
   Compiling ryu v1.0.5
   Compiling proc-macro-hack v0.5.19
   Compiling serde v1.0.123
   Compiling serde_json v1.0.62
   Compiling proc-macro-nested v0.1.7
   Compiling log v0.4.14
   Compiling crossbeam-utils v0.8.1
   Compiling futures-task v0.3.12
   Compiling tokio v1.2.0
   Compiling heck v0.3.2
   Compiling futures-channel v0.3.12
   Compiling bitflags v1.2.1
   Compiling walkdir v2.3.1
   Compiling inventory v0.1.10
   Compiling itertools v0.9.0
   Compiling textwrap v0.11.0
   Compiling aho-corasick v0.7.15
   Compiling bstr v0.2.15
   Compiling terminal_size v0.1.16
   Compiling atty v0.2.14
   Compiling num_cpus v1.13.0
   Compiling shh v1.0.1
   Compiling quote v1.0.9
   Compiling clap v2.33.3
   Compiling textwrap v0.12.1
   Compiling peg-macros v0.6.3
   Compiling regex v1.4.3
   Compiling globset v0.4.6
   Compiling peg v0.6.3
   Compiling ignore v0.4.17
   Compiling globwalk v0.8.1
   Compiling futures-macro v0.3.12
   Compiling thiserror-impl v1.0.23
   Compiling async-stream-impl v0.3.0
   Compiling typed-builder v0.7.1
   Compiling ghost v0.1.2
   Compiling ctor v0.1.19
   Compiling inventory-impl v0.1.10
   Compiling cute_custom_default v2.1.0
   Compiling tokio-macros v1.1.0
   Compiling cucumber_rust_codegen v0.1.0
   Compiling async-trait v0.1.42
   Compiling async-stream v0.3.0
   Compiling futures-util v0.3.12
   Compiling thiserror v1.0.23
   Compiling futures-executor v0.3.12
   Compiling futures v0.3.12
   Compiling gherkin_rust v0.9.0
   Compiling cucumber_rust v0.8.3
error[E0433]: failed to resolve: could not find `cucumber_rust` in crate root
 --> tests/cucumber.rs:5:10
  |
5 | #[derive(WorldInit)]
  |          ^^^^^^^^^ could not find `cucumber_rust` in crate root
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `cucumber_rust` in crate root
  --> tests/cucumber.rs:33:1
   |
33 | #[given("a thing")]
   | ^^^^^^^^^^^^^^^^^^^ could not find `cucumber_rust` in crate root
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `cucumber_rust` in crate root
  --> tests/cucumber.rs:39:1
   |
39 | #[when(regex = "something goes (.*)")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `cucumber_rust` in crate root
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `cucumber_rust` in crate root
  --> tests/cucumber.rs:42:1
   |
42 | #[given("I am trying out Cucumber")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `cucumber_rust` in crate root
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `cucumber_rust` in crate root
  --> tests/cucumber.rs:47:1
   |
47 | #[when("I consider what I am doing")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `cucumber_rust` in crate root
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `cucumber_rust` in crate root
  --> tests/cucumber.rs:53:1
   |
53 | #[then("I am interested in ATDD")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `cucumber_rust` in crate root
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `cucumber_rust` in crate root
  --> tests/cucumber.rs:58:1
   |
58 | #[then(regex = r"^we can (.*) rules with regex$")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `cucumber_rust` in crate root
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `cucumber-example`

To learn more, run the command again with --verbose.

```
Updating the example to the latest release does not fix the issue:
```toml
[package]
name = "cucumber-example"
version = "0.1.0"
authors = ["Aaron Cohen <amcohen@us.ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "0.8.3", features = ["macros"] }
# You can use any executor you want, but we're going to use Tokio in this example.
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
```
